MEN-7788: Use Virtual Device for OS updates in docker composition
mendersoftware/mender-server pull request #227
Opened 2024-11-27 07:48 UTC by lluiscampos

For the upcoming release, we will use the same Virtual Device that we had in the Mender 3.x series. After the release, we will work on migrating to the Virtual Device for app updates consistently across docker composition, ui and docs. See more context in the parent JIRA epic related to this task.

2024-11-27 07:55 UTC, mzedel reviewed
Just to state the obvious: testing this locally it doesn't work as I'm on an arm Mac - so I don't think it's ok for me to approve this.

2024-11-27 08:15 UTC, mzedel commented
To put it into a different context: with the current state I can explore most of the functionality, with this change I can't even see let alone accept a device. also @estenberg

2024-11-27 08:37 UTC, lluiscampos commented
@mzedel I very well understand your concerns. And I think that it is great that you keep voicing this topic in behalf of all Mac ARM users out there.

This PR is a follow-up of yesterday discussion in Grooming meeting with everyone present where the agreement was to postpone the migration to the Virtual Device for app updates to after the release (not to abandon it). We can revert this commit the very same day that we branch out 4.0.x in this repo.

2024-11-27 08:58 UTC, mzedel commented
> This PR is a follow-up of yesterday discussion in Grooming meeting with everyone present where the agreement was to postpone the migration to the Virtual Device for app updates to after the release (not to abandon it). We can revert this commit the very same day that we branch out 4.0.x in this repo.

Completely understand, I just want to point it out at every step of the way as it was ignored for more than 1,5 years (this was likely present well before https://northerntech.atlassian.net/browse/MEN-6407) and now that we finally have it somewhat usable we again make the user experience worse - for every user that tries 4.0 or comes to this repository via the notices in the old service repos. Considering that usability concern have been ignored or pushed back against during grooming meetings long enough I hope this is a more noticeable place to bring these concerns up.
So as a user in the team that is affected by this change I can't approve of it as I will no longer be able to use the composition as is, as long as we have the qemu client - let alone an outside user trying this out.

2024-11-27 19:46 UTC, estenberg commented
We will get this @mzedel , it's just a very bad time to introduce it in the middle of the release process, and the fact that it was partially there was not intended (we can't release half-done replacement). I plan to take it right after the release.

2024-12-03 14:30 UTC, kjaskiewiczz approved these changes, later dismissed

2024-12-03 16:06 UTC, lluiscampos commented
@mzedel I have modified the e2e tests setup to use there the Virtual Device for app updates. You may want to look at that part :eyes: 

@kjaskiewiczz I need your review again because updating the PR dismisses existing approvals :+1:

2024-12-03 20:25 UTC, mzedel requested changes, later dismissed
can you please put the image reference for the device into the e2e compose [here](https://github.com/mendersoftware/mender-server/blob/main/frontend/tests/e2e_tests/docker-compose.e2e-tests.yml#L56-L64) - last we had the qemu client, the tests didn't work with the qemu client and on the main e2e devs machines it doesn't work either + it's a smaller change 🙃

2024-12-04 19:01 UTC, lluiscampos commented
> can you please put the image reference for the device into the e2e compose [here](https://github.com/mendersoftware/mender-server/blob/main/frontend/tests/e2e_tests/docker-compose.e2e-tests.yml#L56-L64) -

I didn't realize that we already had an override for the client service there. Thanks!

> last we had the qemu client, the tests didn't work with the qemu client and on the main e2e devs machines it doesn't work either + it's a smaller change 🙃

Yes, my intention was already to run non-qemu client for e2e tests.

2024-12-06 09:07 UTC, lluiscampos commented
The two failing frontend acceptance tests, `[16/63] 02-layoutAssertions.spec.ts:38:3 › Layout assertions › can authorize a device` and `[26/63] 03-files.spec.ts:184:3 › Files › allows artifact downloads`, also failed in [latest build from `main`](https://gitlab.com/Northern.tech/Mender/mender-server/-/jobs/8561835874), so this PR is not the culprit.

2024-12-06 09:14 UTC, kjaskiewiczz approved these changes

2024-12-06 09:15 UTC, merged