MEN-7838 - text input appearance
mendersoftware/mender-server pull request #271
Opened 2024-12-17 16:21 UTC by mzedel

2024-12-18 08:04 UTC, chiachenglu commented
Nice, thank you! @mzedel Is there also a way for me to see the visual changes too? like clicking around to see how it appears in different places in UI, or I can only see after it is merged and see it on [staging.mender.io](https://staging.hosted.mender.io/ui/)?

2024-12-18 08:10 UTC, aleksandrychev approved these changes, later dismissed

2024-12-18 08:11 UTC, mzedel commented
No unfortunately we don't have preview deployments, but you can run it locally using the image built in CI. I'm sure @alfrunes can help you set this up 😉

2024-12-18 10:11 UTC, chiachenglu commented
Ok, I ran it locally using the image built. I noticed some inconsistencies on the page. For example, some places failed to update to the new variant or did update to the latest variant but did not update its different states. For example, the default state looks correct, but the focus state still looks like the standard variant. Attached are some of the noticeable inconsistencies I noticed. I am guessing these are built in different classes or something which is why it doesn't get to be updated. Nevertheless, let's try to update as much as possible before we publish the changes to make sure we have a consistent look in the most of the pages and features.  @mzedel 

![image (1)](https://github.com/user-attachments/assets/e09d1af0-d5f2-46d5-a685-9bc0e46dba4d)
![image (3)](https://github.com/user-attachments/assets/112b9e3d-430c-449c-a42f-30ff258e175a)
![image (2)](https://github.com/user-attachments/assets/12efcad5-d9a1-49ab-ba46-b5eb00eee2d6)
![image (4)](https://github.com/user-attachments/assets/3c5eef25-932e-45ac-b1e5-cf09555ea2de)
![image (5)](https://github.com/user-attachments/assets/6ff910d6-2156-4f25-9d64-9c13d733d4f9)
![image (6)](https://github.com/user-attachments/assets/a59178ad-c345-4b3b-a2a1-cda543bff0f7)

2024-12-18 10:21 UTC, chiachenglu commented
@michaelntech I am considering to also update the [select property](https://mui.com/material-ui/react-text-field/#select) from standard to outlined variant to get the consistent input field for Mender GUI, What do you think? 
<img width="853" alt="Screenshot 2024-12-18 at 11 18 16" src="https://github.com/user-attachments/assets/54ff9ff0-faee-4e16-9669-77342a75d3ef" />

2024-12-18 10:27 UTC, michaelntech commented
> @michaelntech I am considering to also update the [select property](https://mui.com/material-ui/react-text-field/#select) from standard to outlined variant to get the consistent input field for Mender GUI, What do you think?

Yes, I agree with using outlined everywhere

2024-12-18 10:39 UTC, chiachenglu commented
Awesome, @mzedel kindly update the select property for us as well.

2025-01-08 09:52 UTC, chiachenglu requested changes
Please adjusted the inconsistent places (see above comments).

2025-01-09 17:43 UTC, mzedel commented
> Please adjusted the inconsistent places (see above comments). 

@chiachenglu unfortunately I don't think I will get to it before the end of the sprint 😕

2025-01-10 09:19 UTC, chiachenglu commented
That is no problem. I left the comments so we don't forget to update them. 
Although I am not sure why there are height differences, I guess they are from different sizes of the text input component perhaps (medium and small)? In general, I would expect the text field component to behave and look consistently in its different states (default, hover, focus, disable, and error), whether it is editable or not. So yes, outlined style in disable state too! 👍🏻 

You can view the text field component and how it looks in different states with different properties here: https://www.figma.com/design/e2WPEGusQtx3JnKtOO2san/%F0%9F%8E%B8(UI)-Mender-Design-System-(WIP)?node-id=6570-46740&t=0s73ZMr7eAkjqaen-1

2025-01-21 09:30 UTC, chiachenglu commented
Thanks for the fixes, overall looks good! Only found following things that needs to be final adjusted, and to the rest I think we can create the tickets to adjust further (paddings to other elements and sizes for example). 

![Screenshot 2025-01-21 at 09 42 47](https://github.com/user-attachments/assets/a5407838-26fb-43e1-94a5-ed9736f2547f)

![Screenshot 2025-01-21 at 09 37 11](https://github.com/user-attachments/assets/18c2463c-3045-4c73-8f86-59bdecba3c25)

![Screenshot 2025-01-21 at 09 33 15](https://github.com/user-attachments/assets/2e063529-a337-4c9a-99ea-7190ec392869)

![Screenshot 2025-01-21 at 10 22 33](https://github.com/user-attachments/assets/2b75176d-c040-464f-89d5-ef0f5391d0ef)

![Screenshot 2025-01-21 at 10 20 32](https://github.com/user-attachments/assets/bccb0337-2dd0-43b0-ac63-559f6338edf2)

2025-01-21 09:50 UTC, chiachenglu submitted a review, later dismissed
Please fix the above points before closing the PR.

2025-01-22 08:32 UTC, mzedel commented
There seems to be a steady scope creep happening with every review round 🙃...
 
> ![Screenshot 2025-01-21 at 09 42 47](https://private-user-images.githubusercontent.com/82047138/405150247-a5407838-26fb-43e1-94a5-ed9736f2547f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NjQwNDEsIm5iZiI6MTczNzQ2Mzc0MSwicGF0aCI6Ii84MjA0NzEzOC80MDUxNTAyNDctYTU0MDc4MzgtMjZmYi00M2UxLTk0YTUtZWQ5NzM2ZjI1NDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIxVDEyNDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNTYwMmY3NDFhMDBlMzg0YWZiM2M4YTc4M2I0NzMwYWUzZTRmODM2MTQzMDU1YWQ4NWJjZTFiZDE2ZDg4MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.old7-Aw46qRXqYn9E1HY4vFKd7BwbtQ156ARi03YCoY)

Here the theme default is 14px for the outlined input - I'll revert to that instead, if you actually want the divergence, please include it in one of the follow up tasks.a
> ![Screenshot 2025-01-21 at 09 37 11](https://private-user-images.githubusercontent.com/82047138/405150254-18c2463c-3045-4c73-8f86-59bdecba3c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NjQwNDEsIm5iZiI6MTczNzQ2Mzc0MSwicGF0aCI6Ii84MjA0NzEzOC80MDUxNTAyNTQtMThjMjQ2M2MtMzA0NS00YzczLThmODYtNTliZGVjYmEzYzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIxVDEyNDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDZkMTllMTVmMDRjZThmYzVlZWE4NTg1OWM0ZmViOTRlMTE3Mzg3YmNjNDYxNjNiYTM3YTc2NWZhZjNmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k1h14fx_0CSuC41Vi0UbzraB1gCVtSSf602NdpeVFYQ)

> ![Screenshot 2025-01-21 at 10 22 33](https://private-user-images.githubusercontent.com/82047138/405153536-2b75176d-c040-464f-89d5-ef0f5391d0ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NjQwNDEsIm5iZiI6MTczNzQ2Mzc0MSwicGF0aCI6Ii84MjA0NzEzOC80MDUxNTM1MzYtMmI3NTE3NmQtYzA0MC00NjRmLTg5ZDUtZWYwZjUzOTFkMGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIxVDEyNDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MGE4NDJkZGQ3MGQzYWQzYzYyMzM5MTZkZmFhODk2OTZmZTRiMmUzYzFlZmUxNGE1MTExYmYzNDAxMjcyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HHg_N1Nod2XupGNrd0IvdQJ2UF0tB0j5tRc_r__eoqQ)

> ![Screenshot 2025-01-21 at 10 46 28](https://private-user-images.githubusercontent.com/82047138/405162436-c0a0604e-a08d-4c82-a4a3-471d90e45208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NjQwNDEsIm5iZiI6MTczNzQ2Mzc0MSwicGF0aCI6Ii84MjA0NzEzOC80MDUxNjI0MzYtYzBhMDYwNGUtYTA4ZC00YzgyLWE0YTMtNDcxZDkwZTQ1MjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIxVDEyNDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MmZkOTUxZGJiNjI4YTY2YThmOTFhMmFmM2ZkMGIyNDEzZTc3YTkwMzFmYWU0NGUwOGM0OWRkNzUyM2MyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H0yRFrgrS7mV0WdSZhSbN12PAJQ9EzAic0NZVhOL2tw)

The alignment here is pre-existing, like the device status select, for future review cycles these things should go along with other follow up adjustments.

2025-01-22 10:09 UTC, chiachenglu commented
I agreed some of that we could move to follow-up tasks. Can you share your plan or what needs to be followed up next time? Maybe in the comments. This would help me to review more effectively actually because coming from fresh eyes, I would just blindly expect the UI to look aligned or perfect (at least on the main pages and features) after adaption to the new style. As to the task, did you make any changes or adjustments from the last comments? I tried to fetch the latest changes but I did not see any differences from my local setup. Maybe I miss something? @mzedel

2025-01-22 10:44 UTC, mzedel commented
> I agreed some of that we could move to follow-up tasks. Can you share your plan or what needs to be followed up next time? Maybe in the comments. This would help me to review more effectively actually because coming from fresh eyes, I would just blindly expect the UI to look aligned or perfect (at least on the main pages and features) after adaption to the new style. As to the task, did you make any changes or adjustments from the last comments? I tried to fetch the latest changes but I did not see any differences from my local setup. Maybe I miss something? @mzedel

As to the expectations for what to note in the review: the PR exists in the context of the previous design requirements, so e.g. the role definition/ integrations indentation/ device status selection padding were put there deliberately in the previous designs and thus kept as such. Here I would expect this to be checked against the current state or past designs if unsure and if it's predating the current task and doesn't cause visibility issues (as described in the ticket) => follow up. The user id/ name/ password display e.g. are read only in their current state (user id is always read-only) and as such now diverge from the rest of the UI for read-only values (e.g. device attributes).
With the task at hand in mind, where the description is for now focused on text fields, the review expanded this to other components during the review rounds.

The alignment expectations seem to be a good example as to why "look aligned" or "perfect" is a too subjective matter without a point of reference (as previous design vs. design expectation here seems to diverge - independent of the implementation). I hope that helps to clarify.

As to the content of the PR: Should all be adjusted as requested (except the left padding being 14 instead of 12px to align with the MUI setting there) 👌. It might be required to do a hard reset (e.g. via `git reset mzedel/men-7838 --hard`) - for the future I would be happy to have some more people request feature deployments capabilities to make these PRs easier to review 😄.

2025-01-22 11:00 UTC, mineralsfree approved these changes, later dismissed
Looks good!

2025-01-22 11:00 UTC, mineralsfree commented on frontend/src/js/components/settings/role-management/PermissionsItems.tsx
>      // empty label as a shortcut to align the layout with the select path
remove comment as well?

2025-01-22 11:53 UTC, mzedel commented on frontend/src/js/components/settings/role-management/PermissionsItems.tsx
>      // empty label as a shortcut to align the layout with the select path
Argh, thanks for catching that 🙈 !

2025-01-22 13:17 UTC, mineralsfree approved these changes
:+1:

2025-01-22 14:03 UTC, merged