fix: implement signal handler for `server` commands
mendersoftware/mender-server pull request #274
Opened 2024-12-19 12:06 UTC by bahaa-ghazal

Changelog: Title
Ticket: QA-782

2024-12-19 13:08 UTC, alfrunes requested changes
This is looking pretty good, your PR is capturing the full coverage report. I only have a couple minor change requests. I didn't want to repeat myself, but I see the change is the same for all 4 files changed so the comments also apply there.

2024-12-19 13:08 UTC, alfrunes commented on backend/services/deployments/server.go
> +		l.Fatal("error when shutting down the server ", err)
Can we log the error to the `Error` stream and pass the error to the parent function?
```suggestion
		l.Errorf("error when shutting down the server: %s", err.Error())
		return err
```

2024-12-19 13:08 UTC, alfrunes commented on backend/services/deployments/server.go
> +	<-quit
If the go routine created here terminates unexpectedly, this process will continue to run doing nothing until a signal is received. We need some way of notifying the "parent" go routine that the "child" is stopping. You could for example achieve this by creating an additional `chan`nel to pass the error from the child and use a [select](https://go.dev/tour/concurrency/5) statement to listen on both `chan`nels.
```suggestion
	errChan := make(chan error, 1)
	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			errChan <- err
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, unix.SIGINT, unix.SIGTERM)
	select {
	case sig := <-quit:
		l.Infof("received signal %s: terminating", sig)
	case err = <-errChan:
		l.Errorf("server terminated unexpectedly: %s", err.Error())
		return err
	}
```

2025-01-01 09:48 UTC, alfrunes commented on backend/services/deployments/server.go
> +		l.Infof("received signal %s: terminating", sig)
I think you accidentally removed the call to `Server.Shutdown`. Can you please bring it back and add it to this `case`?

2025-01-01 12:11 UTC, bahaa-ghazal commented on backend/services/deployments/server.go
> +		l.Infof("received signal %s: terminating", sig)
I see, that was a stupid  mistake.  I just added `Server.Shutdown` before returning. Thanks for the review!

2025-01-02 09:10 UTC, alfrunes reviewed
Just one small thing before I click the green button :monocle_face:

2025-01-02 09:10 UTC, alfrunes commented on backend/services/deployments/server.go
> +		l.Fatal("error when shutting down the server ", err)
Can you change the log level to `Error` please? :upside_down_face:

2025-01-03 07:22 UTC, alfrunes approved these changes

2025-01-08 15:57 UTC, merged

2025-01-09 14:45 UTC, oldgiova commented
Just a nitpick suggestion for the next time: by using a `fix:` commit message, this change will be published in the public changelog: https://github.com/mendersoftware/mender-server/pull/309/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR20

Maybe a different commit message for the next time? Like `chore:` or `misc:`, if you don't want this note to go public ;)

2025-01-09 15:20 UTC, mzedel commented
or use `Changelog: None` - since we have the comfort to opt out of the changelog, while using a fitting scope 😉